// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9s1heuvV_lG4hi6F3EAHlbPQIzy4kFw',
    appId: '1:628236276796:web:5dee8dfaf113b1e2c0df39',
    messagingSenderId: '628236276796',
    projectId: 'flatmate-aef67',
    authDomain: 'flatmate-aef67.firebaseapp.com',
    storageBucket: 'flatmate-aef67.appspot.com',
    measurementId: 'G-BDTSR5MPKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZmporkHNiF_rE3h41Nrohy_CYBXEzBs',
    appId: '1:628236276796:android:5fd0aae750482c89c0df39',
    messagingSenderId: '628236276796',
    projectId: 'flatmate-aef67',
    storageBucket: 'flatmate-aef67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfXtv32u3W8absQlI5BHMSwqafCjKnk_U',
    appId: '1:628236276796:ios:8b2f8ba4dbe50fc8c0df39',
    messagingSenderId: '628236276796',
    projectId: 'flatmate-aef67',
    storageBucket: 'flatmate-aef67.appspot.com',
    iosBundleId: 'com.example.flatmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfXtv32u3W8absQlI5BHMSwqafCjKnk_U',
    appId: '1:628236276796:ios:8b2f8ba4dbe50fc8c0df39',
    messagingSenderId: '628236276796',
    projectId: 'flatmate-aef67',
    storageBucket: 'flatmate-aef67.appspot.com',
    iosBundleId: 'com.example.flatmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN9s1heuvV_lG4hi6F3EAHlbPQIzy4kFw',
    appId: '1:628236276796:web:555306c2cd99f411c0df39',
    messagingSenderId: '628236276796',
    projectId: 'flatmate-aef67',
    authDomain: 'flatmate-aef67.firebaseapp.com',
    storageBucket: 'flatmate-aef67.appspot.com',
    measurementId: 'G-XCXZ6GBNMZ',
  );
}
